pipeline {
  agent any

  environment {
    AWS_ACCESS_KEY_ID     = credentials('aws-access')     
    AWS_SECRET_ACCESS_KEY = credentials('aws-secret')     
  }

  stages {
    stage('Clone Repo') {
      steps {
        checkout scm
      }
    }

    stage('Terraform Init') {
      steps {
        dir('eks') {
          sh 'terraform init'
        }
      }
    }

    stage('Terraform Plan') {
      steps {
        dir('eks') {
          sh 'terraform plan'
        }
      }
    }

    stage('Terraform Apply') {
      steps {
        dir('eks') {
          sh 'terraform apply -auto-approve'
        }
      }
    }
  }
}
